name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      # Ensure the required version is up to date
      - name: Update the Required Config Node version
        run: node ./.github/scripts/update-required-config-node-version.js

      - name: Build
        run: npm run build

      - name: Publish package to public npm registry
        uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          tag: ${{ contains(github.ref, '-beta') && 'beta' || contains(github.ref, '-alpha') && 'alpha' || 'latest' }}
          token: ${{ secrets.NPM_TOKEN }}
