name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: read
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      # Ensure the required version is up to date
      - name: Update the Required Config Node version
        run: node ./.github/scripts/update-required-config-node-version.js

      - name: Build
        run: npm run build

      - name: Publish package to public npm registry
        uses: JS-DevTools/npm-publish@v4
        with:
          access: public
          ignore-scripts: true
          provenance: true
          tag: ${{ contains(github.ref, '-beta') && 'beta' || contains(github.ref, '-alpha') && 'alpha' || 'latest' }}

  # TODO: Use a webhook because sleep is not ideal
  update-library:
    needs: publish-npm
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes
        run: sleep 5m

      - name: Update Node-RED flow-library
        uses: BigThunderSR/update-package-node-red-flow-library-action@v1.3.11
        with:
          package-name: '@gogovega/node-red-contrib-firebase-realtime-database'
