name: Tests

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'assets/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          RTDB_URL: ${{ secrets.RTDB_URL }}
          BRANCH_REF: ${{ github.ref }}
